#!/bin/bash
# Description: Script for creating test files, the amount of which is specified by the user

echo -n "How many test files do you want to create? "
read AMOUNT

# How the user input is piped in the for loop
for i in $(seq 1 $AMOUNT)
  do
    echo "Creating test file number $i"
    touch testfile_$i.tst
  done

# Creating multiple files with a command is just like
# touch test{1..3}.test
