#!/bin/bash
# Description: Script for printing the file contents with line numbers using while

# Argument check
if [ $# -ne 1 ]; then
  echo "Exactly only one argument is needed $0 <filepath>"
  exit 1
fi

# check if provided arguments is a file
if ! [ -f $1 ]; then
  echo "File does not exist"
  exit 2
fi

FILENAME=$1
COUNT=1

# Second way of reading a file
cat $FILENAME | 
while read line
  do
  echo "$COUNT: $line"
  let COUNT++
done

