#!/bin/bash
# Description: Script that checks the provided argument and if it is an IP address- check whether it is reachable or not

# Argument check
if [ $# -ne 1 ]; then
  echo "Please provide only one argument. Enter $0 <some argument>"
  exit 1
fi

CAPTURED_VAR=$1
#IP address regex
IP_REGEX="([0-9]{1,3}\.?){4}"

# Regex check
if ! [[ $CAPTURED_VAR =~ $IP_REGEX ]]; then
  echo "No IP address provided"
  exit 2
fi

# Capture the regex match
IP=${BASH_REMATCH[0]}

# ping the ip
ping -c3 $IP 1> /dev/null
if [ $? -eq 0 ]; then
  STATUS="Alive"
else
  STATUS="Not reachable"
fi

echo "IP found ($IP) with status: $STATUS"
