#!/bin/bash
# Description short if statement test
# && - if the exit status of the previous command is 0
# || - if the exit status of the previous command is !=0

echo -n "Your AGE? " 
read AGE

# The syntax is as follow
# if the second command is surrounded with () => it is executed in a different shell so the exit status will be 1 and all messages will be shown 
[ $AGE -lt 20 ] && { echo "You are not allowed to see this message"; exit 1; } || echo "Hello"

echo "The SECRET message"

